# Generated by Django 2.2.8 on 2020-04-11 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EffectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(default='Not provided')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameStructureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('img_path', models.TextField(default='./src/assets/building.png')),
                ('round_frequency', models.IntegerField(default=1)),
                ('assortment_range', models.IntegerField(default=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemEffectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.EffectModel')),
            ],
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(default='Not provided')),
                ('img_path', models.TextField(default='./src/assets/skill.jpeg')),
                ('cost', models.IntegerField()),
                ('effects', models.ManyToManyField(blank=True, through='game.ItemEffectModel', to='game.EffectModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillEffectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.EffectModel')),
            ],
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(default='Not provided')),
                ('img_path', models.TextField(default='./src/assets/skill.jpeg')),
                ('effects', models.ManyToManyField(blank=True, through='game.SkillEffectModel', to='game.EffectModel')),
                ('requirements', models.ManyToManyField(blank=True, related_name='_skillmodel_requirements_+', to='game.SkillModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpellEffectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.EffectModel')),
            ],
        ),
        migrations.CreateModel(
            name='SpellModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(default='Not provided')),
                ('img_path', models.TextField(default='./src/assets/skill.jpeg')),
                ('cost', models.IntegerField()),
                ('effects', models.ManyToManyField(blank=True, through='game.SpellEffectModel', to='game.EffectModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('health', models.IntegerField(default=50)),
                ('damage', models.IntegerField(default=3)),
                ('attack_range', models.IntegerField(default=1)),
                ('move_range', models.IntegerField(default=1)),
                ('armor', models.IntegerField(default=2)),
                ('level', models.IntegerField(default=1)),
                ('img_path', models.TextField(default='./src/assets/unit.jpeg')),
                ('items', models.ManyToManyField(blank=True, to='game.ItemModel')),
                ('skills', models.ManyToManyField(blank=True, to='game.SkillModel')),
                ('spells', models.ManyToManyField(blank=True, to='game.SpellModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='spelleffectmodel',
            name='spell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.SpellModel'),
        ),
        migrations.AddField(
            model_name='skilleffectmodel',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.SkillModel'),
        ),
        migrations.AddField(
            model_name='itemeffectmodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.ItemModel'),
        ),
        migrations.CreateModel(
            name='HeroModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.IntegerField(default=50)),
                ('damage', models.IntegerField(default=3)),
                ('attack_range', models.IntegerField(default=1)),
                ('move_range', models.IntegerField(default=1)),
                ('armor', models.IntegerField(default=2)),
                ('name', models.CharField(max_length=50)),
                ('img_path', models.TextField(default='./src/assets/board_hero_sized.png')),
                ('items', models.ManyToManyField(blank=True, to='game.ItemModel')),
                ('skills', models.ManyToManyField(blank=True, to='game.SkillModel')),
                ('spells', models.ManyToManyField(blank=True, to='game.SpellModel')),
                ('suit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_suit', to='game.ItemModel')),
                ('weapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_weapon', to='game.ItemModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('round', models.IntegerField(default=1)),
                ('state', models.TextField(default='{}')),
                ('hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.HeroModel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
