# Generated by Django 2.2.2 on 2019-08-10 17:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('effects', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='hero',
            name='items',
        ),
        migrations.AddField(
            model_name='hero',
            name='items',
            field=models.ManyToManyField(to='game.Item'),
        ),
        migrations.RemoveField(
            model_name='hero',
            name='skills',
        ),
        migrations.AddField(
            model_name='hero',
            name='skills',
            field=models.ManyToManyField(to='game.Skill'),
        ),
        migrations.RemoveField(
            model_name='hero',
            name='spells',
        ),
        migrations.AddField(
            model_name='hero',
            name='spells',
            field=models.ManyToManyField(to='game.Spell'),
        ),
        migrations.RemoveField(
            model_name='skill',
            name='requirements',
        ),
        migrations.AddField(
            model_name='skill',
            name='requirements',
            field=models.ManyToManyField(related_name='_skill_requirements_+', to='game.Skill'),
        ),
        migrations.AddField(
            model_name='item',
            name='effects',
            field=models.ManyToManyField(to='game.Effect'),
        ),
        migrations.AddField(
            model_name='skill',
            name='effects',
            field=models.ManyToManyField(to='game.Effect'),
        ),
        migrations.AddField(
            model_name='spell',
            name='effects',
            field=models.ManyToManyField(to='game.Effect'),
        ),
    ]
