# Generated by Django 2.2.8 on 2020-04-03 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStructureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('img_path', models.TextField(default='./src/assets/building.png')),
                ('round_frequency', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemEffectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.EffectModel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.ItemModel')),
            ],
        ),
    ]
