# Generated by Django 2.2.4 on 2019-10-13 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190810_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='items',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='knowledge',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='leadership',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='item',
            name='limb',
        ),
        migrations.AddField(
            model_name='effect',
            name='description',
            field=models.TextField(default='Not provided'),
        ),
        migrations.AddField(
            model_name='hero',
            name='armor',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='hero',
            name='attack_range',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hero',
            name='damage',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='hero',
            name='health',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='hero',
            name='img_path',
            field=models.TextField(default='./src/assets/hero.jpeg'),
        ),
        migrations.AddField(
            model_name='hero',
            name='suit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_suit', to='game.Item'),
        ),
        migrations.AddField(
            model_name='hero',
            name='weapon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_weapon', to='game.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Not provided'),
        ),
        migrations.AddField(
            model_name='item',
            name='img_path',
            field=models.TextField(default='./src/assets/item.jpeg'),
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(default='Not provided'),
        ),
        migrations.AddField(
            model_name='skill',
            name='img_path',
            field=models.TextField(default='./src/assets/skill.jpeg'),
        ),
        migrations.AddField(
            model_name='spell',
            name='description',
            field=models.TextField(default='Not provided'),
        ),
        migrations.AddField(
            model_name='spell',
            name='img_path',
            field=models.TextField(default='./src/assets/spell.jpeg'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='effects',
            field=models.TextField(),
        ),
    ]
